version: "3"

services:
  postgres:
    image: postgres:13
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - terra
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

networks:
  terra:
    driver: bridge
